### ISSUE TITLE
Data import from CLI does not work in 0.11.4

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#451]
<a href="https://github.com/nickluger"><img src="https://avatars1.githubusercontent.com/u/32647249?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nickluger](https://github.com/nickluger)**
_Sunday Jan 07, 2018 at 14:33 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1535_

----

**Current behavior**

`gcf import --source ./seed.zip` leads to:

```shell config definitionPath null +0ms
  config homepath /Users/xxx/.graphcoolrc +0ms
  config localRCPath /Users/xxx/xxx/xxxx/.graphcoolrc +0ms
  config globalRCPath /Users/nick/.graphcoolrc +0ms
TypeError: Cannot read property 'modules' of undefined
    at Import.<anonymous> (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/src/commands/import/index.ts:39:47)
    at step (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:42:23)
    at Object.next (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:23:53)
    at fulfilled (/Users/nick/.config/yarn/global/node_modules/graphcool-cli-core/dist/commands/import/index.js:14:58)
    at <anonymous>
Exiting with code: 1
```

**Reproduction**

I'm using `graphcool-framework/0.11.4`. It's installed globally. This error happens for any zip file. Even if i put a movie in it, so i assume its not a problem with the data...

**Expected behavior?**

It should import data correctly.

**Comment by marktani** [comment]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marktani](https://github.com/marktani)**
_Sunday Jan 07, 2018 at 14:37 GMT_

----

Could you please provide a minimal example that reproduces this error? 🙂 

It should contain

* a `graphcool.yml` and `types.graphql` file
* an `seed.zip` file

Thanks!

**Comment by marktani** [comment]
<a href="https://github.com/nickluger"><img src="https://avatars1.githubusercontent.com/u/32647249?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nickluger](https://github.com/nickluger)**
_Monday Jan 08, 2018 at 05:33 GMT_

----

Hey thank you for the fast answer! 😃   here's the example!

I'm sorry, i was invoking the command from another directory. The error is resolved, if invoked from the project folder. 

But even if i get no error message now, 

**no data gets imported, if i zip the files manually** 

using any zip tool.

You can check this out:  https://github.com/nickluger/graphcool-manual-zip-error

If i `gcf import --source export-2018-01-08T05/13/08.150Z.zip` i get all data imported correctly. I assume it uses this [exporter](https://github.com/graphcool/graphcool/blob/df3765220ff6c049e99369a76676d2b1e746cd5c/cli/packages/graphcool-cli-core/src/commands/export/Exporter.ts). 

The file `seed.zip` was created by unzipping `export-2018-01-08T05/13/08.150Z.zip` and simply rezipping it via `zip -r seed.zip export-2018-01-08T05/13/08.150Z.zip`. 

If you `gcf import --source seed.zip`, you get no error, but there is no data imported neither..

**Comment by marktani** [comment]
<a href="https://github.com/nickluger"><img src="https://avatars1.githubusercontent.com/u/32647249?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nickluger](https://github.com/nickluger)**
_Monday Jan 08, 2018 at 05:46 GMT_

----

I'm currently using this for seeding. I have a seed directory checked out in source control and would like to seed the database using something like `zip -r ...  && gcf import ...`. If there is a smarter or alternative way to [seed the db](https://github.com/graphcool/graphcool/issues/1536), i would be happy to know. 😄

**Comment by jharmon141** [comment]
I get this error when running `prisma import --data ./data.zip`:

`Unzipping... ⢿
raven@2.3.0 alert: failed to send exception to sentry: HTTP Error (413): undefined
Error: invalid signature: 0xa
    at /usr/local/lib/node_modules/prisma/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)`

**Comment by WirthAware** [comment]
I have the same issue with `graphcool-framework 0.11.5` 
Running it localy with `npx`
Also tested it running with global install, with same effect  
Also tested installing `graphcool-framework` as global, with same error  

```
npx graphcool import --source data/<name>.zip --target <target_name>
```

```
graphcool -v
graphcool-framework/0.11.5 (darwin-x64) node-v8.7.0
```

```
Unzipping... ⣯
raven@2.4.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
Error: invalid signature: 0x80014
    at /<project>/node_modules/unzip/lib/parse.js:59:13
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by marktani** [comment]
Hey @Melv, when you unzip the folder and import the unzipped folder, does it work then?

**Comment by steve-a-jones** [comment]
Wrote a quick to get this to work.. (see  graphcool-cli-core/dist/commands/import)

```Importer.prototype.unzip = function () {
        var _this = this;
        return new Promise(function (resolve, reject) {
            var before = Date.now();
            _this.out.action.start('Unzipping');

            Minizip.unzip(_this.importPath, _this.importDir, function(err) {
                if (err)
                  console.log(err);
                else {
                    _this.out.action.stop(chalk_1.default.cyan(Date.now() - before + "ms"));
                    resolve();
                }
                 
            });

            // var output = unzip.Extract({ path: _this.importDir });
            // fs.createReadStream(_this.importPath).pipe(output);
            // output.on('close', function () {
            //     _this.out.action.stop(chalk_1.default.cyan(Date.now() - before + "ms"));
            //     resolve();
            // });
        });
    };
```

But now I am getting another error `Field type Json has no validator defined`. Is importing `Json` not supported?

**Comment by niwaa** [comment]
@steve-a-jones 

I think I found a workaround fix: 

In : graphcool/node_modules/graphcool-cli-core/dist/commands/import/Importer.js

Replace the node-unzip library with this one: https://github.com/EvanOxfeld/node-unzip (after installing it as a dependency).

```
// var unzip = require("unzip");
var unzip = require("unzip-stream");
```
I was able to import 20k sample nodes on mac-os, but will do more testing.

**Comment by juanpprieto** [comment]
I'm also getting this error I'm afraid. 

I get the error with both the untouched exported zip and also if I re-zip the folder.
`graphcool-framework/0.11.5 (darwin-x64) node-v9.2.1`
